version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build_script:
  build.bat

after_build:
  - ps: dir

test: off

deploy:
  provider: NuGet
  api_key:
    secure: er/U2/CvQ1PB7fzqLd58D6wEGLFo7jaOu1Id6ruQ8OeMckIgwqSXBtIz0rbIs3pQ
  artifact: /.*\.nupkg/